server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/productdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Mo?esz da?: none, validate, update, create, create-drop
    properties:
      hibernate:
    #        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true        # Pokazuje zapytania w logach
    format_sql: true      # Formatowanie SQL w logach